version: '3'

services:
  rails: &rails
    build:
      context: .
      dockerfile: ./compose/development/rails/Dockerfile
    image: selfcare_system_development_rails
    depends_on:
      - mysql
      - redis
    volumes:
      - selfcare_system_development_rails_sprockets_cache:/rails_sprockets_cache
      - .:/app
    tty: true      
    ports:
      - "3000:3000"
    env_file:
      - ./.envs/.development/.rails
      - ./.envs/.development/.mysql
      - ./.envs/.development/.redis
    environment: 
      - RAILS_SPROCKETS_CACHE=/rails_sprockets_cache      
    command: /start

  redis:
    image: redis:6.0.4-alpine

  mysql:
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - selfcare_system_development_mysql_data:/var/lib/mysql
    env_file: 
      - ./.envs/.development/.mysql
    
volumes:
  selfcare_system_development_rails_sprockets_cache:
  selfcare_system_development_mysql_data: