version: '3'

services:
  rails:
    build:
      context: ./rails
      dockerfile: ./Dockerfile
    links:
      - mysql:mysql
    depends_on:
      - mysql
    command: sh
    tty: true
    volumes:
      - ./rails:/opt/SelfcareSystem
    ports:
      - "3000:3000"
  mysql:
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    
volumes:
  mysql_db: