development:
  adapter: redis
  host: <%= ENV["REDIS_HOST"] %>
  port: <%= ENV["REDIS_PORT"] %>
  channel_prefix: <%= ENV["REDIS_CHANNEL_PREFIX"] %>
  
test:
  adapter: async

production:
  adapter: redis
  host: <%= ENV["REDIS_HOST"] %>
  port: <%= ENV["REDIS_PORT"] %>
  channel_prefix: <%= ENV["REDIS_CHANNEL_PREFIX"] %>
