#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

bundle exec rails db:create
bundle exec rails db:migrate
bundle exec rails assets:precompile
rm -f /app/tmp/pids/server.pid
bundle exec rails server